# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: arigonza <arigonza@student.42malaga.com>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/06 14:15:10 by arigonza          #+#    #+#              #
#    Updated: 2023/05/06 15:18:40 by arigonza         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = MINITALK

CC = gcc

CFLAGS = -Wall -Werror -Wextra

SRC = ./clientc \
	  ./server.c \

OBJ = $(SRC:.c=.o)

all : $(NAME)
